spring.application.name=journalBot

spring.datasource.url=jdbc:postgresql://localhost:8081/journalBot
spring.datasource.username=postgres
spring.datasource.password=jovaji143

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
